name: CI/CD-frontend
on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Tests
      run: |
        yarn frontend:tests-ci

    - name: Lint
      run: |
        yarn lint:fix

    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        add: 'frontend/src'
        message: 'Commit from GitHub Actions: lint autofix'

    - name: Build
      run: |
        yarn frontend:build

    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        add: 'frontend/build'
        message: 'Commit from GitHub Actions: build'